/**
 * Generated by orval v8.12.1 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */
import type { AnchorRecipientRequest } from './anchorRecipientRequest';
import type { LabelRecipientRequest } from './labelRecipientRequest';
import type { ManualRecipientRequest } from './manualRecipientRequest';

export interface BuzzCreateRequest {
  text: string;
  recipient: AnchorRecipientRequest | LabelRecipientRequest | ManualRecipientRequest;
  imageKeys?: string[];
}
