/**
 * Generated by orval v8.12.1 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */
import type { BuzzProfileResult } from './buzzProfileResult';

export interface BuzzSummaryResult {
  buzzId?: string;
  author?: BuzzProfileResult;
  text?: string;
  imageUrls?: string[];
  commentCount?: number;
  remainingMinutes?: number;
  isUnread?: boolean;
  isCreator?: boolean;
}
