/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */
import type { LabelRecipientRequest } from './labelRecipientRequest';
import type { ManualRecipientRequest } from './manualRecipientRequest';
import type { PivotRecipientRequest } from './pivotRecipientRequest';

export interface BuzzCreateRequest {
  text: string;
  recipient: LabelRecipientRequest | ManualRecipientRequest | PivotRecipientRequest;
}
