/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */
import type { BuzzCommentRequest } from './buzzCommentRequest';

export type CommentBody = {
  request: BuzzCommentRequest;
  images?: Blob[];
};
