/**
 * Generated by orval v8.12.1 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */
import type { MemorialSeedItem } from './memorialSeedItem';
import type { ScheduleSeedItem } from './scheduleSeedItem';

export interface FlagSeedItem {
  title?: string;
  status?: string;
  schedule?: ScheduleSeedItem;
  capacity?: number;
  participantUserIds?: number[];
  memorials?: MemorialSeedItem[];
}
