/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */

export type FriendRequestResultStatus = typeof FriendRequestResultStatus[keyof typeof FriendRequestResultStatus];


export const FriendRequestResultStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  HIDDEN: 'HIDDEN',
} as const;
