/**
 * Generated by orval v8.12.1 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */

export interface FriendUpdateRequest {
  /**
     * @minLength 1
     * @maxLength 20
     */
  friendAlias?: string;
  isMuted?: boolean;
  isRoutable?: boolean;
}
