/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */
import type { UserReference } from './userReference';

export interface Friendship {
  id?: string;
  createdAt?: string;
  intimacy?: number;
  users?: UserReference[];
}
