/**
 * Generated by orval v8.12.1 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */

export type GetRecentFlagsRole = typeof GetRecentFlagsRole[keyof typeof GetRecentFlagsRole];


export const GetRecentFlagsRole = {
  HOST: 'HOST',
  PARTICIPANT: 'PARTICIPANT',
} as const;
