/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */
import type { RecipientRequest } from './recipientRequest';

export type ManualRecipientRequest = RecipientRequest & {
  /**
     * @minItems 0
     * @maxItems 150
     */
  memberIds: number[];
};
