/**
 * Generated by orval v8.12.1 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */
import type { SortObject } from './sortObject';

export interface PageableObject {
  offset?: number;
  sort?: SortObject;
  unpaged?: boolean;
  paged?: boolean;
  pageSize?: number;
  pageNumber?: number;
}
