/**
 * Generated by orval v8.12.1 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */
import type { RecipientRequest } from './recipientRequest';

export type PivotRecipientRequest = RecipientRequest & {
  pivotFriendId: number;
  /**
     * @minimum 0
     * @maximum 1
     */
  expansionValue: number;
};
