/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */

export interface SignupRequestDto {
  email: string;
  /**
     * @minLength 2
     * @maxLength 20
     */
  nickname: string;
  /** @pattern ^(?=.*[A-Za-z])(?=.*\d)(?=.*[!@#$%^&*])[A-Za-z\d!@#$%^&*]{8,20}$ */
  password: string;
}
