/**
 * Generated by orval v8.12.1 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */
import type { FlagResult } from './flagResult';
import type { PageableObject } from './pageableObject';
import type { SortObject } from './sortObject';

export interface SliceFlagResult {
  size?: number;
  content?: FlagResult[];
  number?: number;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageable?: PageableObject;
  empty?: boolean;
}
