/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */
import type { BuzzSummaryResult } from './buzzSummaryResult';
import type { PageableObject } from './pageableObject';
import type { SortObject } from './sortObject';

export interface SliceBuzzSummaryResult {
  size?: number;
  content?: BuzzSummaryResult[];
  number?: number;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageable?: PageableObject;
  empty?: boolean;
}
