/**
 * Generated by orval v8.12.1 🍺
 * Do not edit manually.
 * DunbarHorizon API 명세서
 * DunbarHorizon 백엔드 API
 * OpenAPI spec version: 1.0.0
 */

export interface UserProfileUpdateRequest {
  /**
     * @minLength 2
     * @maxLength 20
     */
  nickname: string;
  profileImageKey?: string;
}
